language: node_js

node_js:
 - 0.6
 - 0.8

branches:
  only:
    - Unstable
    - master
    - testing

services:
 - mongodb
 - redis-server

install:
 - npm install

before_script:
 - node src/listener.js > /dev/null 2>&1 &
 - node src/consumer.js > /dev/null 2>&1 &
